# 03 - Vectorized Operations

## 🎯 Objective
**Stop thinking in loops** — learn to think vectorized naturally.

## 🤖 AI Relevance
**This is how model weights update.** In deep learning:
- Weight updates are vectorized operations across entire layers
- Batch processing = vectorized operations on multiple samples
- GPU acceleration works because of vectorization

**Loops are 10-100x slower than vectorized operations.** If you write loops in NumPy, you're doing it wrong.

In [ ]:
import numpy as np

---
## 📖 Concept 1: Element-wise Operations

Operations apply to every element automatically — **no loops needed!**

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print("Original:", arr)

# Element-wise operations
print("Add 10:", arr + 10)        # [11, 12, 13, 14, 15]
print("Multiply by 2:", arr * 2)  # [2, 4, 6, 8, 10]
print("Square:", arr ** 2)        # [1, 4, 9, 16, 25]
print("Divide by 2:", arr / 2)    # [0.5, 1.0, 1.5, 2.0, 2.5]

---
## 📖 Concept 2: Array-to-Array Operations

Operations between two arrays work element-wise.

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print("a:", a)
print("b:", b)
print("\na + b:", a + b)  # [11, 22, 33, 44]
print("a * b:", a * b)    # [10, 40, 90, 160]
print("b - a:", b - a)    # [9, 18, 27, 36]
print("b / a:", b / a)    # [10.0, 10.0, 10.0, 10.0]

---
## 📖 Concept 3: Broadcasting

**Broadcasting** allows operations between arrays of different shapes. NumPy automatically "stretches" the smaller array.

In [ ]:
# Broadcasting with scalar (we've been doing this!)
arr = np.array([1, 2, 3])
print("arr * 10:", arr * 10)  # [10, 20, 30]

In [ ]:
# Broadcasting with different shapes
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row = np.array([10, 20, 30])

print("Matrix:\n", matrix)
print("\nRow:", row)
print("\nMatrix + Row:\n", matrix + row)
# The row is added to each row of the matrix!

---
## 📖 Concept 4: Why Vectorized > Loops

Let's compare performance.

In [ ]:
import time

# Create large array
arr = np.random.rand(1000000)

# Method 1: Loop (slow)
start = time.time()
result_loop = []
for x in arr:
    result_loop.append(x * 2)
time_loop = time.time() - start

# Method 2: Vectorized (fast)
start = time.time()
result_vec = arr * 2
time_vec = time.time() - start

print(f"Loop time: {time_loop:.4f} seconds")
print(f"Vectorized time: {time_vec:.6f} seconds")
print(f"\nSpeedup: {time_loop / time_vec:.1f}x faster!")

---
## ✍️ Practice Tasks

### Task 1: Multiply all values by 2

In [ ]:
arr = np.array([5, 10, 15, 20, 25])
# Your code here


### ✅ Solution

In [ ]:
# Solution
arr = np.array([5, 10, 15, 20, 25])
result = arr * 2
print("Result:", result)

### Task 2: Add two arrays together

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
# Your code here


### ✅ Solution

In [ ]:
# Solution
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
result = a + b
print("Result:", result)

### Task 3: Normalize an array (subtract mean, divide by std)

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
# Your code here
# Hint: Use np.mean() and np.std()


### ✅ Solution

In [ ]:
# Solution
arr = np.array([10, 20, 30, 40, 50])
normalized = (arr - np.mean(arr)) / np.std(arr)
print("Normalized:", normalized)
print("Mean after normalization:", np.mean(normalized))  # Should be ~0
print("Std after normalization:", np.std(normalized))    # Should be ~1

### Task 4: Multiply a 5×3 matrix by scalar 3

In [ ]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12],
                   [13, 14, 15]])
# Your code here


### ✅ Solution

In [ ]:
# Solution
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12],
                   [13, 14, 15]])
result = matrix * 3
print("Result:\n", result)

### Task 5: Add a 1D array to every row of a 2D array (broadcasting)

In [ ]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
row = np.array([100, 200, 300])
# Your code here


### ✅ Solution

In [ ]:
# Solution
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
row = np.array([100, 200, 300])
result = matrix + row
print("Result:\n", result)
# Broadcasting adds the row to each row of the matrix!

---
## 🧠 Predict the Output

### Challenge 1: What happens when you add a (3,) array to a (3,3) matrix?

In [ ]:
# Predict first, then run
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr = np.array([10, 20, 30])
print(matrix + arr)

**Your prediction:** *(Write it down before running)*

**Answer:** The 1D array is broadcast (added) to each row:
```
[[11 22 33]
 [14 25 36]
 [17 28 39]]
```

### Challenge 2: What is the result of np.array([1,2,3]) ** 2?

In [ ]:
# Predict first, then run
result = np.array([1, 2, 3]) ** 2
print(result)

**Your prediction:** *(Write it down before running)*

**Answer:** [1 4 9] — Each element squared

### Challenge 3: What is the shape of the result?

In [ ]:
# Predict first, then run
matrix = np.ones((4, 5))
scalar = 10
result = matrix * scalar
print("Result shape:", result.shape)

**Your prediction:** *(Write it down before running)*

**Answer:** (4, 5) — Same as input matrix. Scalar broadcasting doesn't change shape.

---
## 🎯 Key Takeaways

1. **Vectorized > Loops** — Always prefer vectorized operations (10-100x faster)
2. **Element-wise by default** — Operations apply to every element automatically
3. **Broadcasting is magic** — NumPy automatically handles compatible shapes
4. **Think in arrays, not loops** — This is the NumPy mindset
5. **Common operations:** `+`, `-`, `*`, `/`, `**` all work element-wise

**Next:** Move on to `04_matrix_arithmetic.ipynb` to learn about matrix multiplication! 🚀